config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/' => 'blogs#index'
  get 'blogs/new' => 'blogs#new'
  post 'blogs' => 'blogs#create'
  delete 'blogs/:id' => 'blogs#destroy'
  get 'blogs/:id/edit' => 'blogs#edit'
  patch 'blogs/:id/edit' => 'blogs#update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :blogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  def index
    @blogs = Blog.includes(:user).order("created_at DESC").page(params[:page]).per(20)
  end

  def new
    @blog = Blog.new
  end

  def create
    Blog.create(title: blog_params[:title],text: blog_params[:text], image: blog_params[:image], size: blog_params[:size], user_id: current_user.id)
  end

  def destroy
    blog = Blog.find(params[:id])
    blog.destroy if blog.user_id == current_user.id
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    blog = Blog.find(params[:id])
    blog.update(title: params[:title],text: params[:text], image: params[:image], size: params[:size], user_id: current_user.id) if blog.user_id == current_user.id
  end

  private
    def blog_params
      params.require(:blog).permit(:title, :text, :image, :size).merge(user_id: current_user.id)

    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blog.html.erb
  <div class="col s<%= blog.size %>">
    <div class="card">
      <div class="card-image">
        <img src="<%= blog.image %>">
        <span class="card-title"><%= blog.title %></span>
      </div>
      <div class="card-content">
        <p><%= blog.text %></p>
      </div>
      <div class="card-action">
        <a href="#">詳細</a>
        <% if user_signed_in? && current_user.id == blog.user_id %>
          <%= link_to '編集', "/blogs/#{blog.id}/edit" %>
          <%= link_to '削除', "/blogs/#{blog.id}", method: :delete %>
        <% end %>
      </div>
    </div>
  </div>

app/views/blogs/create.html.erb
  <div class="row">
    <div class="col s12 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">投稿完了</span>
          <p>投稿ご苦労様です！せっかくご投稿していただいたのですが、誰もみてくれないかもしれません。誰もコメントしてくれないかもしれません。でも、大丈夫！きっといいことがあります！！挫けず毎日投稿するよう心掛けましょう！</p>
        </div>
        <div class="card-action">
          <a href="/">top に戻る</a>
        </div>
      </div>
    </div>
  </div>

app/views/blogs/destroy.html.erb
  <div class="row">
    <div class="col s12 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">削除完了</span>
          <p>あーあ、勿体無い。なんてことしてくれてるんですか！？あなたこの記事書くのに4時間も費やしてましたよね？※※※※なの！？</p>
        </div>
        <div class="card-action">
          <a href="/">仕方ないので top に戻る</a>
        </div>
      </div>
    </div>
  </div>

app/views/blogs/edit.html.erb
  <div class="row container">
    <%= form_for "#{@blog}", method: :patch do |f| %>
      <div class="row">
        <div class="input-field col s4  ">
          <%= f.text_field :title, placeholder: 'title', value: "#{@blog.title}",name: "title", class: "materialize-textarea", id: "textarea1"%>
          <label for="textarea1">Title</label>
        </div>
        <div class="input-field col s10">
          <%= f.text_area :text, placeholder: 'write here FREELY!', value: "#{@blog.text}", name: "text", class: "materialize-textarea", id: "textarea2"%>
          <label for="textarea2">Blog text</label>
        </div>
        <div class="input-field col s10">
          <%= f.text_field :image, placeholder: 'past image url link', value: "#{@blog.image}", name: "image", class: "materialize-textarea", id: "textarea2"%>
          <label for="textarea3">Image</label>
        </div>
        <div class="input-field col s10">
          <%= f.number_field :size, value: "#{@blog.size}",min: 2, max:12, name: "size", class: "materialize-textarea", id: "textarea4"%>
          <label for="textarea4">size (2~12のお好きな数字を今日のあなたの気分で入力！)</label>
        </div>
      </div>
      <div class="row">
        <div class="col10 push1">
          <%= button_tag type: "submit", class: "btn btn--block" do %>
            編集する
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

app/views/blogs/index.html.erb
<div class="row">


  <% @blogs.each do |blog| %>
    <%= render partial: "blog", locals: {blog: blog} %>
  <% end %>

  <div class="col s8">
    <div class="card">
      <div class="card-image">
        <img src="https://www.readersdigest.ca/wp-content/uploads/sites/14/2011/01/4-ways-cheer-up-depressed-cat.jpg">
        <span class="card-title">Card Title</span>
      </div>
      <div class="card-content">
        <p>I am a very simple card. I am good at containing small bits of information.
        I am convenient because I require little markup to use effectively.</p>
      </div>
      <div class="card-action">
        <a href="#">This is a link</a>
      </div>
    </div>
  </div>

  <div class="col s2">
    <div class="card">
      <div class="card-image">
        <img src="https://netflix-fan.jp/wp-content/uploads/2018/02/mechanic2_copy_1050_591_81_s_c1.jpg">
        <span class="card-title">Card Title</span>
      </div>
      <div class="card-content">
        <p>I am a very simple card. I am good at containing small bits of information.
        I am convenient because I require little markup to use effectively.</p>
      </div>
      <div class="card-action">
        <a href="#">This is a link</a>
      </div>
    </div>
  </div>
  <div class="col s2">
    <div class="card">
      <div class="card-image">
        <img src="http://livedoor.blogimg.jp/zzcj/imgs/7/0/70bea02c.jpg">
        <span class="card-title">Card Title</span>
      </div>
      <div class="card-content">
        <p>I am a very simple card. I am good at containing small bits of information.
        I am convenient because I require little markup to use effectively.</p>
      </div>
      <div class="card-action">
        <a href="#">This is a link</a>
      </div>
    </div>
  </div>

  <div class="col s4  ">
    <div class="card">
      <div class="card-image">
        <img src="http://penina-cvitanic.si/en/images/Sparkling-wine-Cvitanic-and-green-apple-coctail.jpg">
        <span class="card-title">Card Title</span>
      </div>
      <div class="card-content">
        <p>I am a very simple card. I am good at containing small bits of information.
        I am convenient because I require little markup to use effectively.</p>
      </div>
      <div class="card-action">
        <a href="#">This is a link</a>
      </div>
    </div>
  </div>

  <div class="col s4  ">
    <div class="card">
      <div class="card-image">
        <img src="https://i.ytimg.com/vi/G7E9TXOZ1i0/maxresdefault.jpg">
        <span class="card-title">Card Title</span>
      </div>
      <div class="card-content">
        <p>I am a very simple card. I am good at containing small bits of information.
        I am convenient because I require little markup to use effectively.</p>
      </div>
      <div class="card-action">
        <a href="#">This is a link</a>
      </div>
    </div>
  </div>

  <div class="col s8  ">
    <div class="card">
      <div class="card-image">
        <img src="https://cdn.vox-cdn.com/thumbor/wng90rt7pFT3o_oPRNV21iK-2x8=/0x0:4560x3041/1200x800/filters:focal(1916x1157:2644x1885)/cdn.vox-cdn.com/uploads/chorus_image/image/58504395/911428568.jpg.0.jpg">
        <span class="card-title">Card Title</span>
      </div>
      <div class="card-content">
        <p>I am a very simple card. I am good at containing small bits of information.
        I am convenient because I require little markup to use effectively.</p>
      </div>
      <div class="card-action">
        <a href="#">This is a link</a>
      </div>
    </div>
  </div>
</div>

app/views/blogs/new.html.erb
  <div class="row container">
    <%= form_for @blog do |f| %>
      <div class="row">
        <div class="input-field col s4  ">
          <%= f.text_field :title, placeholder: 'title', value: '', class: "materialize-textarea", id: "textarea1"%>
          <%= label :title, :title %>
        </div>
        <div class="input-field col s10">
          <%= f.text_area :text, placeholder: 'write here FREELY!', value: '', class: "materialize-textarea", id: "textarea2"%>
          <%= label :text, :blog %>
        </div>
        <div class="input-field col s10">
          <%= f.text_field :image, placeholder: 'past image url link', value: '', class: "materialize-textarea", id: "textarea3"%>
          <%= label :image, :image %>
        </div>
        <div class="input-field col s10">
          <%= f.number_field :size, value: '3',min: 2, max:12, class: "materialize-textarea", id: "textarea4"%>
          <%= label :size, :"(2~12のお好きな数字を今日のあなたの気分で入力！)" %>
        </div>
      </div>
      <div class="row">
        <div class="col10 push1">
          <%= button_tag type: "submit", class: "btn btn--block" do %>
            投稿する
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

app/views/blogs/update.html.erb
  <div class="row">
    <div class="col s12 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">変更完了</span>
          <p>粋なことしてくれるじゃねぇか。俺様がコメントした内容とテメーのブログとの内容が噛み合わなくなっちまってるじゃねぇか！</p>
        </div>
        <div class="card-action">
          <a href="/">仕方ないので top に戻る</a>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiniBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Compiled and minified CSS -->
    <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css" %>
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
    <script
      src="https://code.jquery.com/jquery-3.3.1.js"
      integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
      crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="nav-extended teal lighten-2">
      <div class="nav-wrapper">
        <a href="/" class="brand-logo">Logo</a>
        <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
        <% if user_signed_in? %>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><a href="sass.html">マイページ</a></li>
            <li><%= link_to '投稿', blogs_new_path %></li>
            <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
          </ul>
          <ul class="side-nav" id="mobile-demo">
            <li><a href="sass.html">Sass</a></li>
            <li><a href="badges.html">Components</a></li>
            <li><a href="collapsible.html">JavaScript</a></li>
          </ul>
        <% else %>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><%= link_to '新規登録', new_user_registration_path %></li>
            <li><%= link_to 'ログイン',new_user_session_path %></li>
          </ul>
          <ul class="side-nav" id="mobile-demo">
            <li><a href="sass.html">Sass</a></li>
            <li><a href="badges.html">Components</a></li>
            <li><a href="collapsible.html">JavaScript</a></li>
          </ul>
        <% end %>
      </div>
      <div class="nav-content">
        <ul class="tabs tabs-transparent">
          <li class="tab"><a href="#test1">Test 1</a></li>
          <li class="tab"><a class="active" href="#test2">Test 2</a></li>
          <li class="tab"><a href="#test3">Test 3</a></li>
          <li class="tab"><a href="#test4">Test 4</a></li>
        </ul>
      </div>
    </nav>


    <%= yield %>


    <footer class="page-footer teal lighten-2">
      <div class="container">
        <div class="row">
          <div class="col l6 s12">
            <h5 class="white-text">Footer Content</h5>
            <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
          </div>
          <div class="col l4 offset-l2 s12">
            <h5 class="white-text">Links</h5>
            <ul>
              <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
              <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
              <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
              <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="footer-copyright">
        <div class="container">
        © 2014 Copyright Text
        <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
        </div>
      </div>
    </footer>
  </body>
</html>